ARDUINO_DIR = /usr/share/arduino

#TARGET       = CLItest
#ARDUINO_LIBS = LiquidCrystal

MCU          = atmega328p
F_CPU        = 16000000
ARDUINO_PORT = /dev/ttyUSB0

AVRDUDE_ARD_PROGRAMMER = arduino
AVRDUDE_ARD_BAUDRATE   = 57600
#AVRDUDE_ARD_EXTRAOPTS  = -F

include /usr/share/arduino/Arduino.mk


prova:
	$(REMOVE) -r build-cli

